version: "3.3"
services:
  db:
    restart: always
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
    expose:
    - 3306
  # bot:
  #   restart: always
  #   build: 
  #     context: bot
  #   depends_on:
  #     - survival
  survival:
    restart: always
    build: 
      context: minecraft
    depends_on:
      - db
    volumes:
      - ./worlds:/worlds
    expose:
      - 25565
  waterfall:
    restart: always
    build: waterfall
    ports: 
    - 25565:25577
volumes:
  worlds:
# networks: 
#   front:
#     driver: bridge
#   back: